project:
  type: website

website:
  title: "e-fl√¢neur"
  navbar:
    right:
      - icon: github
        href: https://github.com/shriv
      - icon: twitter
        href: https://twitter.com/ShrividyaRavi
    left:
      - text: "Blog"
        file: blog.qmd
      - text: "Essays"
        file: essays.qmd
      - text: "About"
        file: index.qmd

format:
  html:
    theme: cosmo
    css: styles.css



